# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: MacBook-Pro

    steps:
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest pythontest.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
